### PR TITLE
Iss41take2

### PR DESCRIPTION
**Pull request by rruenroeng**
This is the first bit of code that gets us towards an image uploader. It brings a bunch of packages along for the ride, but it does a lot of nice handling and error checking that we couldn't build very easily. Let me know what you think.

### CODE REVIEW

**Comment by alex-sherman** [comment]
It looks like this only uploads the images on the client so far. Should this PR also include the logic for storing the images on the server, or should that go in separately?

**Comment by DarrenZLew** [comment]
We'll need to add the http request to post the file. Then store the image file to the server side.

We'll also need the http request to get the image file from the server side and display the image on the client side.

Rather than merging this right now, let's add all of the above first.

**Comment by rruenroeng** [comment]
Living and learning. I was gonna baby step through this one. Does take2
make sense to implement? It pulls in a lot of dependencies, but it also
does a lot of nice handling. I'm going to look into coding the server side
stuff tomorrow.

Always happy to meet up/discuss parts of the project.

**Comment by DarrenZLew** [comment]
It's fine as long as you're planning to implement the server side portion as well.

**Review by DarrenZLew — APPROVED** [review]

**Pull request merged**
