### PR TITLE
Create ProfileForm and link it up to App.js

### PR DESCRIPTION
**Pull request by rruenroeng**
Hi guys,

I started working on the profile page. I based a lot of it off of Darren's ScoreForm. Could you please review what I have and let me know if I can pull it in? I only created the profile page for now. We should design what fields should go into it in a separate issue and I'd be happy to work on that. 

Let me know your thoughts.

-Do Fun Stuff
Ryan

### CODE REVIEW

**Comment by sandasai** [comment]
Looks fine. 

We are starting to add a lot of test data directly in the App.js component. I prefer not to do this since data will kind of be everywhere and messy.

Instead what we can do is start connecting the components to redux reducers. You can look at my Login.js component as an example. Essentially, just make a reducer for each app module that we have. In my case, I kept all the authorization/authentication stuff in the Auth reducer. The test data can then be put into the initial state of the reducer.

For now I'm okay merging it into Master but we would still need to link it to redux eventually.

**Comment by DarrenZLew** [comment]
This looks good to me as well, for now. As for the test data, you should follow what Sanda recommends. I have removed the test data currently in the App.js component into its own redux reducer for the Score Form. I just need to commit my changes.

**Comment by rruenroeng** [comment]
Sounds good. I opened a new issue to track the need to put the data into a redrux reducer. I'll merge these changes to master and close this issue.

**Comment by rruenroeng** [comment]
https://github.com/DarrenZLew/FantasyFitness-1.0/issues/19

UserName: Can't be edited.

Nickname - League Nickname - any validation?

Email: Since we aren't doing password resets at this time, can we just let
them edit this freely? Standard email validation

Phone Number?

Favorite Food:

Any other fields we should be adding?

Best,
Ryan

**Pull request merged**
